# Generated by Django 2.2.24 on 2023-03-22 20:28

from django.db import migrations


def push_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner, defaults={
            'owners_phonenumber': flat.owners_phonenumber,
            'owner_pure_phone': flat.owner_pure_phone
        })

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20230323_0020'),
    ]

    operations = [migrations.RunPython(push_owners)
    ]
