# Generated by Django 2.2.24 on 2023-03-23 02:32

from django.db import migrations


def set_flats_to_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all():
        owner.flats.set(Flat.objects.filter(
            owner=owner.owner,
            owners_phonenumber=owner.owners_phonenumber))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230323_0630'),
    ]

    operations = [ migrations.RunPython(set_flats_to_owners),
    ]
