# Generated by Django 2.2.24 on 2023-03-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230328_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
        migrations.RenameField(
            model_name='сomplaint',
            old_name='complain_content',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='сomplaint',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='property.Flat', verbose_name='Квартира, на которую пожаловались'),
        ),
    ]
